### PR TITLE
Add CMAKE_PREFIX_PATH to readme example of how to build cppmm

### PR DESCRIPTION
**Pull request by luke-titley**
I had to add CMAKE_PREFIX_PATH to env when configuring. To pick up cmake modules from llvm.

### CODE REVIEW

**Comment by anderslanglands** [comment]
Hmm interesting. What's your cmake/os/llvm version combo? It works fine for me with 3.17/ubuntu18/10.0.1 - I would have thought FindLLVM.cmake should have found this automatically.

**Comment by luke-titley** [comment]
Mojave (10.14.6)
cmake 3.19.0 (installed with homebrew)
llvm 11.0.0 (binary downloaded directly from website and just extracted next to cppmm clone)

My install of cmake doesn't come with FindLLVM (there's no cmake module for it in "/usr/local/share/cmake/Module") (maybe it does with ubunutu dpkg), it seems FindLLVM comes with llvm itself (10 and above), so unless it's installed system wide or I set CMAKE_PREFIX_PATH somewhere manually it won't get picked up.

I thought it would be useful to mention this in the readme, so that it's quicker for anyone who hits this problem next time around. Not that it took that much time to find the problem really.

That additional set in the env seems likely to cover all bases...

**Comment by lgritz** [comment]
You shouldn't need FindLLVM.cmake module any more. You only need that for old packages that don't export a config file.

For packages that support it, you should prefer an exported set of targets in LLVMConfig.cmake, which is usually found in the package's lib/cmake directory. That's the modern way to do things. It should be found if either CMAKE_PREFIX_PATH includes the project, or for a particular project, you should be able to just set LLVM_ROOT=/path/to/llvm/install (either as a CMake variable or an environment variable) and it will all just work.

**Comment by luke-titley** [comment]
ok. More investigation. You can throw away this merge request. I used a relative path for LLVM_ROOT which was causing the issue. With an absolute path I don't need CMAKE_PREFIX_PATH.

**Pull request closed without merging**
