### PR TITLE
Move stream insertion namespace

### PR DESCRIPTION
**Pull request by luke-titley**
I'm on mac, compiled with apple clang 11.0.0.
I couldn't get cppmm to build without this change.

### CODE REVIEW

**Comment by anderslanglands** [comment]
Looks like this mixes up the llvm 11 changes from your other PR? I'll try
doing this on my local branch and see if it still builds correctly with gcc.

**Comment by luke-titley** [comment]
oops. sorry, I meant to keep them separate. Should have double checked the diff.

**Comment by luke-titley** [comment]
k. as you merged the llvm-11 request. I've rebased this on the latest main.

**Comment by anderslanglands** [comment]
I'm going to close this as I've just added loggin via spdlog which has meant updating to latest fmt, which will change how formatting overloads are defined.

**Pull request closed without merging**
