### PR TITLE
cmake: install astgen and asttoc

### PR DESCRIPTION
**Pull request by davvid**
Update the build system to install `astgen` and `asttoc`.

Adjust the installation paths to use conventional locations from the FIlesystem Hierarchy Standard.

### CODE REVIEW

**Comment by anderslanglands** [comment]
Copying David's comments and questions here from slack:
```
I'm starting to play around with cppmm. I've gotten as far as being able to generate the std  bindings (with some local tweaks). First, here's a PR I put together with some basic stuff to make astgen/asttoc a little more like a typical installable package[1].
While going through the std example I had a few questions:
* There are a few scripts (eg. tests/bindandtest.sh) that refer to a ./cppmm executable. Are these stale? I didn't see a cppmm command being generated so I'm assuming it's been replaced by astgen and asttoc. Is that correct?
  * the readme also mentions cppmm btw -- does that need updating?
* For some reason the std bindings kept complaining about missing move constructors, and I was only able to get past the astgen step by adding basic_string() CPPMM_IGNORE = default; to test/std/bind/std_string.cpp.
* After the out/ directory has been generated, what's the process to transform the generated cmake and out/std_string* into a rust crate?
```
First of all, thanks for the PR! I'm going to hold off merging it for now as we're a ways away from considering this something installable. I'll probably merge it some time over the next few weeks when a good moment presents itself.

In answer to your questions:
1. Yes these are old and I need to remove them. What is now astgen and asttoc used to be a single cppmm binary.
2. Not sure about that one it doesn't happen for me. What version of clang are you using and on what platform?
3. That will be handled either by asttoc or another binary which hasn't been written yet.

**Comment by davvid** [comment]
Thanks for shuffling the slack Qs over here; noted for future since github is probably an easier place for external folks to find details.  Thanks for the notes, things are starting to become clearer after reading through the issues and learning about the cppmm -> ast{gen,toc} split.

I'm currently testing using llvm 10.0.1 on macOS catalina / xcode 12.4. I'll be testing on debian/testing (and maybe rhel7) later as well.

I cobbled my llvm build together and didn't include libcxx and libcxxabi originally so I'll try rebuilding with these components enabled to see if it makes a difference. Here is the exact error I was seeing:

```
cppmm/test/std/bind/std_string.cpp:23:3: error: no matching
      constructor for initialization of 'class basic_string'
} CPPMM_OPAQUEBYTES;
  ^
cppmm/test/std/bind/std_string.cpp:9:7: note: candidate
      constructor (the implicit copy constructor) not viable: requires 1 argument, but 0
      were provided
class basic_string {
      ^
cppmm/test/std/bind/std_string.cpp:9:7: note: candidate
      constructor (the implicit move constructor) not viable: requires 1 argument, but 0
      were provided
cppmm/test/std/bind/std_string.cpp:18:5: note: candidate
      constructor not viable: requires 3 arguments, but 0 were provided
    basic_string(const char* s, ::std::string::size_type count,
    ^
1 error generated.
Error while processing cppmm/test/std/bind/std_string.cpp.
```

My `-I` include paths are different than what we have in `bind.sh` here (I had to point to a homebrew gcc's include directory for the c++ headers) so I'm guessing that's the source of this difference; I'm way off the reservation so I guess it's surprising that it even worked at all ;-)

Heh, I've gone way out of scope for this PR with these questions. I'll leave this PR open per your notes. I'll be using astgen/asttoc in their installed configuration and I'll make myself available to address any notes or questions that come up.

Thanks again for your help.

**Comment by luke-titley** [comment]
A very quick comment to say there is a bind.sh script at the top of the rep which is how I run astgen+asttoc.
It shows you at least examples of the input flags. Likely that will be deleted/moved at some point in the future though.

**Comment by davvid** [comment]
Thanks Luke. I've now tried both LLVM 10.0.1 and 11.0.0 (built from source) as well as the pre-built LLVM 11 binaries from https://releases.llvm.org/download.html -- they all behave the same and only get past the astgen step if I modify the `basic_string` std_string.cpp type to include a default constructor: `basic_string() = default;`

I've taken homebrew's gcc out of the equation -- I'm just using clang + stock xcode 12 now. I wonder if it's because of differences in macOS / xcode / libc++ versions?  The generated json is very different. Here is a diff snippet that shows that the repo has a `std::__cxx11` namespace in its `test/std/ref/ast/std_string.json` and locally I'm getting a `std::__1` namespace. cxx11 is gnu's namespace IIRC.

```
     "decls": [
         {
             "kind": "Namespace",
-            "name": "std::__cxx11",
-            "id": 9,
-            "short_name": "__cxx11"
+            "name": "std::__1",
+            "id": 12,
+            "short_name": "__1"
         }
```

Another clue is this removal that's visible in the json diff. 

```
-                {
-                    "kind": "Field",
-                    "name": "",
-                    "type": {
-                        "kind": "RecordType",
-                        "id": 28,
-                        "type": "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::(anonymous at /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:171:7)",
-                        "record": -1,
-                        "const": false
-                    }
-                }
```

Note the `/usr/lib/gcc/x86_64-linux-gnu/....` path. It suggests that the type came from `/usr/lib/gcc/x86_64-linux-gnu/10/../../../include/c++/10/bits/basic_string.h` which does not exist locally here as far as I can tell. I wonder if this is a compiler-rt difference in that I'm using libc++ with the `std::__1` namespace from the libc++ headers.

What xcode version and macOS version are you using? It seems like the reference json was generated using gcc's headers, so maybe I'm just hitting a difference in the c++ libraries and the tweak to add `basic_string() = default;` to the std_string.cpp bind file is needed in this configuration?

```
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

It's kinda funny that it mentions `--with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1` because that directory doesn't even exist. I wonder if this is the root cause (that newer xcode versions don't provide the gcc headers under the isysroot).

For completeness, this is the shell script I'm running. LLVM_ROOT contains the pre-built llvm 11 binaries from releases.llvm.org:

```
#!/bin/sh
LLVM_ROOT="$HOME/src/clang+llvm-11.0.0-x86_64-apple-darwin"
clang_version=11.0.0
macos_sdk=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
cppmm=$HOME/src/rust/cppmm

main () {
    cd "$cppmm/build" &&
    ./astgen/astgen \
        ../test/std/bind \
        -u \
        -o ../test/std/ref/ast \
        -i $PWD/../test/std/bind \
        -rust-sys $PWD/../test/std/test-rust-sys \
        -- \
        -I$cppmm/test \
        -isysroot$macos_sdk \
        -isystem $macos_sdk/usr/include \
        -isystem $LLVM_ROOT/lib/clang/$clang_version/include \
        -isystem $LLVM_ROOT/include/c++/v1 \
        &&
    # Generate the cpp
    rm -rf out &&
    mkdir -p out &&
    ./asttoc/asttoc -o out -l m ../test/std/ref/ast
}

main "$@"
```

I have to include an extra `-isystem $macos_sd/usr/include` which `bind.sh` does not have. If I remove `-isystem $macos_sdk/usr/include` then astgen segfaults after hitting a handful of errors that all look like:

```
In file included from cppmm/test/std/bind/std_string.cpp:1:
In file included from clang+llvm-11.0.0-x86_64-apple-darwin/include/c++/v1/string:506:
In file included from clang+llvm-11.0.0-x86_64-apple-darwin/include/c++/v1/string_view:175:
In file included from clang+llvm-11.0.0-x86_64-apple-darwin/include/c++/v1/__string:57:                                                                   In file included from clang+llvm-11.0.0-x86_64-apple-darwin/include/c++/v1/algorithm:642:
In file included from clang+llvm-11.0.0-x86_64-apple-darwin/include/c++/v1/utility:204:
clang+llvm-11.0.0-x86_64-apple-darwin/include/c++/v1/cstdint:157:8
: error: no member named 'uint8_t' in the global namespace
using::uint8_t;
```

which again looks like a mixing of headers. I wonder if it's because I upgraded to xcode 12 recently (reflected in the `g++ --version` output above).

```
$ readlink /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
MacOSX10.15.sdk
```

I should probably test on linux ;-). Was `test/std/ref/ast/std_string.json` generated on linux? Was `bind.sh` written using macOS with an older xcode? It should be noted that, with the tweaks in place, it is able to get to the `asttoc` step and generate the `out/` directory.

 Unsurprisingly, the generated code uses the `std::__1` namespaces rather than `std::__cxx11` like we see in `test/std/ref/c/std_string_private.h`.

For reference, here is the generated `std_string.h` in this configuration:

```

typedef struct std___1_string_s {
    char data[24];
} __attribute__((aligned(8))) std___1_string;


void std___1_string_basic_string(
    std___1_string * self);


std___1_string * std___1_string_assign(
    std___1_string * self
    , char * s
    , unsigned long count);


char * std___1_string_c_str(
    std___1_string const * self);

```

Thanks for your help, let me know if there's anything else I can probe and share that'll help diagnose the platform differences.

**Comment by luke-titley** [comment]
Hey, thanks for all the info.

For clarity I'm going to use libstdc++ for gnu stl and libc++ for clang.

I've not hit the `basic_string() = default;` issue I'm on Mojav 10.14.16 with clang+llvm 11.0 and libc++.
I *think* @anderslanglands is on linux using clang 10 and libstdc++ (If I get into helping out with astgen then I'll be switching to clang 10).

The error 'no member named 'uint8_t' in the global namespace' I recognise. If you try switching astgen.cpp line 102 from #if 1 to #if 0, then the clang headers bundled with astgen will be ignored and you'll be able to use your own.

As you've noted, going from the stl ast checked in, is not a good idea right now, best to generate on the platform you're developing on. I think in the future we'll figure out how to deal with that properly, but for now we're just trying to get other things solved, like more coverage of c++ and making the bind files quicker to write/maintain.

Really appreciate the sleuth work, and if you've got more time to contribute to asttoc or astgen, that would be amazing also.

**Comment by anderslanglands** [comment]
Yep I’m on Ubuntu 18.04. I was on llvm 10 but now on 11.

**Comment by davvid** [comment]
Sweet, thanks for the notes. Indeed, changing astgen.cpp line 102 did get it past that part and now it just complains about the constructors as before (where adding a default one makes it happy).

**Comment by luke-titley** [comment]
ah, we'll need to add that to the bind file then. Maybe you can put that in this PR ?

**Comment by davvid** [comment]
Thanks for verifying. I opened up a separate PR for the constructor stuff since it seemed orthogonal to the cmake enhancements in this branch.

**Comment by anderslanglands** [comment]
Closing as I've manually added this to main now.

**Pull request closed without merging**
